# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_gitikar_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_history', models.CharField(blank=True, max_length=1000, null=True)),
                ('members', models.ManyToManyField(to='album.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='gitikar',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='gitikar',
            name='biography',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
