# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_auto_20160210_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Artists',
        ),
    ]
