# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0008_auto_20160210_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prokashok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
