# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0009_auto_20160210_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Shilpi',
        ),
    ]
