# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0011_auto_20160210_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_history', models.CharField(blank=True, max_length=1000, null=True)),
                ('members', models.ManyToManyField(to='album.Shilpi')),
            ],
        ),
    ]
