# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0013_auto_20160210_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albumname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('album_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('album_no', models.IntegerField(blank=True, null=True)),
                ('lineup', models.ManyToManyField(to='album.Shilpi')),
                ('prokashok', models.ManyToManyField(to='album.Prokashok')),
            ],
        ),
    ]
