# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0014_albumname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lyric', models.CharField(blank=True, max_length=5000, null=True)),
                ('albumname', models.ManyToManyField(blank=True, null=True, to='album.Albumname')),
                ('bandname', models.ManyToManyField(blank=True, null=True, to='album.Bandname')),
                ('gitikar', models.ManyToManyField(blank=True, null=True, to='album.Gitikar')),
                ('shilpi', models.ManyToManyField(blank=True, null=True, to='album.Shilpi')),
            ],
        ),
    ]
