# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0015_gaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gaan',
            options={'verbose_name': '\u0997\u09be\u09a8', 'verbose_name_plural': '\u0997\u09be\u09a8\u0997\u09c1\u09b2\u09cb'},
        ),
        migrations.AlterField(
            model_name='gaan',
            name='albumname',
            field=models.ManyToManyField(blank=True, null=True, to='album.Albumname', verbose_name='\u098f\u09b2\u09ac\u09be\u09ae'),
        ),
        migrations.AlterField(
            model_name='gaan',
            name='bandname',
            field=models.ManyToManyField(blank=True, null=True, to='album.Bandname', verbose_name='\u09ac\u09cd\u09af\u09be\u09a8\u09cd\u09a1'),
        ),
        migrations.AlterField(
            model_name='gaan',
            name='gitikar',
            field=models.ManyToManyField(blank=True, null=True, to='album.Gitikar', verbose_name='\u0997\u09c0\u09a4\u09bf\u0995\u09be\u09b0'),
        ),
        migrations.AlterField(
            model_name='gaan',
            name='lyric',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u0997\u09be\u09a8'),
        ),
        migrations.AlterField(
            model_name='gaan',
            name='shilpi',
            field=models.ManyToManyField(blank=True, null=True, to='album.Shilpi', verbose_name='\u09b6\u09bf\u09b2\u09cd\u09aa\u09c0'),
        ),
        migrations.AlterField(
            model_name='gaan',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u09b6\u09bf\u09b0\u09cb\u09a8\u09be\u09ae'),
        ),
        migrations.AddField(
            model_name='gaan',
            name='catagory',
            field=models.ManyToManyField(blank=True, null=True, to='album.Catagory', verbose_name='\u09aa\u09cd\u09b0\u0995\u09be\u09b0'),
        ),
    ]
