# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0016_auto_20160215_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(max_length=500, verbose_name='\u09ac\u09bf\u09ad\u09be\u0997'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='short_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u09ac\u09bf\u09ac\u09b0\u09a8'),
        ),
    ]
