# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0017_auto_20160215_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name': '\u09b6\u09cd\u09b0\u09c7\u09a3\u09c0\u09ac\u09bf\u09ad\u09be\u0997', 'verbose_name_plural': '\u09ac\u09bf\u09ad\u09be\u0997 \u09b8\u09ae\u09c2\u09b9'},
        ),
        migrations.AlterField(
            model_name='gaan',
            name='catagory',
            field=models.ManyToManyField(blank=True, null=True, to='album.Catagory', verbose_name='\u09b6\u09cd\u09b0\u09c7\u09a3\u09bf\u09ac\u09bf\u09ad\u09be\u0997'),
        ),
    ]
