# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0018_auto_20160215_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumname',
            options={'verbose_name': '\u098f\u09b2\u09ac\u09be\u09ae', 'verbose_name_plural': '\u098f\u09b2\u09ac\u09be\u09ae\u0997\u09c1\u09b2\u09cb'},
        ),
        migrations.AlterModelOptions(
            name='bandname',
            options={'verbose_name': '\u09ac\u09cd\u09af\u09be\u09a8\u09cd\u09a1', 'verbose_name_plural': '\u09ac\u09cd\u09af\u09be\u09a8\u09cd\u09a1\u09a6\u09b2'},
        ),
        migrations.AlterModelOptions(
            name='gitikar',
            options={'verbose_name': '\u0997\u09c0\u09a4\u09bf\u0995\u09be\u09b0', 'verbose_name_plural': '\u0997\u09c0\u09a4\u09bf\u0995\u09be\u09b0\u0997\u09a3'},
        ),
        migrations.AlterModelOptions(
            name='prokashok',
            options={'verbose_name': '\u09aa\u09cd\u09b0\u0995\u09be\u09b6\u0995', 'verbose_name_plural': '\u09aa\u09cd\u09b0\u0995\u09be\u09b6\u0995\u09ac\u09c3\u09a8\u09cd\u09a6'},
        ),
        migrations.AlterModelOptions(
            name='shilpi',
            options={'verbose_name': '\u09b6\u09bf\u09b2\u09cd\u09aa\u09c0', 'verbose_name_plural': '\u09b6\u09bf\u09b2\u09cd\u09aa\u09c0\u09ac\u09c3\u09a8\u09cd\u09a6'},
        ),
        migrations.AlterField(
            model_name='albumname',
            name='album_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u098f\u09b2\u09ac\u09be\u09ae \u09a8\u09be\u09ae\u09cd\u09ac\u09be\u09b0'),
        ),
        migrations.AlterField(
            model_name='albumname',
            name='album_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u09ac\u09bf\u09ac\u09b0\u09a8'),
        ),
        migrations.AlterField(
            model_name='albumname',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u09a8\u09be\u09ae'),
        ),
        migrations.AlterField(
            model_name='bandname',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u09a8\u09be\u09ae'),
        ),
        migrations.AlterField(
            model_name='bandname',
            name='short_history',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u09ac\u09bf\u09ac\u09b0\u09a8'),
        ),
        migrations.AlterField(
            model_name='gitikar',
            name='biography',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u09ac\u09bf\u09ac\u09b0\u09a8'),
        ),
        migrations.AlterField(
            model_name='gitikar',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u09a8\u09be\u09ae'),
        ),
        migrations.AlterField(
            model_name='prokashok',
            name='name',
            field=models.CharField(max_length=150, verbose_name='\u09a8\u09be\u09ae'),
        ),
        migrations.AlterField(
            model_name='prokashok',
            name='short_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u09ac\u09bf\u09ac\u09b0\u09a8'),
        ),
        migrations.AlterField(
            model_name='shilpi',
            name='biography',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u09ac\u09bf\u09ac\u09b0\u09a8'),
        ),
        migrations.AlterField(
            model_name='shilpi',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u09a8\u09be\u09ae'),
        ),
    ]
