# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0019_auto_20160216_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitikar',
            old_name='title',
            new_name='name',
        ),
    ]
