# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0020_auto_20160217_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumname',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='bandname',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='gitikar',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='prokashok',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='shilpi',
            old_name='name',
            new_name='title',
        ),
    ]
