# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0021_auto_20160217_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='name',
            new_name='title',
        ),
    ]
