# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0022_auto_20160217_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chobi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u09b6\u09bf\u09b0\u09cb\u09a8\u09be\u09ae')),
                ('chobi', models.ImageField(default=b'pic_folder/None/no-img.jpg', upload_to=b'pic_folder/')),
            ],
        ),
    ]
