# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0023_chobi'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumname',
            name='chobi',
            field=models.ManyToManyField(to='album.Chobi'),
        ),
        migrations.AlterField(
            model_name='chobi',
            name='chobi',
            field=models.ImageField(default=b'pic_folder/None/no-img.jpg', upload_to=b'pic_folder/', verbose_name='\u099b\u09ac\u09bf'),
        ),
    ]
