# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0028_auto_20160313_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaan',
            name='gitikar',
            field=models.ManyToManyField(blank=True, null=True, to='album.Shilpi', verbose_name='\u0997\u09c0\u09a4\u09bf\u0995\u09be\u09b0'),
        ),
        migrations.AlterField(
            model_name='gaan',
            name='shilpi',
            field=models.ManyToManyField(blank=True, null=True, related_name='_gaan_shilpi_+', to='album.Shilpi', verbose_name='\u09b6\u09bf\u09b2\u09cd\u09aa\u09c0'),
        ),
    ]
