# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0029_auto_20160314_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumname',
            name='lead_guitar',
            field=models.ManyToManyField(blank=True, null=True, related_name='_albumname_lead_guitar_+', to='album.Shilpi', verbose_name='\u09b2\u09bf\u09a1 \u0997\u09bf\u099f\u09be\u09b0'),
        ),
        migrations.AlterField(
            model_name='albumname',
            name='voice',
            field=models.ManyToManyField(blank=True, null=True, related_name='_albumname_voice_+', to='album.Shilpi', verbose_name='\u0995\u09a8\u09cd\u09a0'),
        ),
    ]
