# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0030_auto_20160314_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumname',
            name='lead_guitar',
            field=models.ManyToManyField(blank=True, null=True, related_name='alb_lg', to='album.Shilpi', verbose_name='\u09b2\u09bf\u09a1 \u0997\u09bf\u099f\u09be\u09b0'),
        ),
        migrations.AlterField(
            model_name='albumname',
            name='voice',
            field=models.ManyToManyField(blank=True, null=True, related_name='alb_voice', to='album.Shilpi', verbose_name='\u0995\u09a8\u09cd\u09a0'),
        ),
        migrations.AlterField(
            model_name='gaan',
            name='gitikar',
            field=models.ManyToManyField(blank=True, null=True, related_name='ga_git', to='album.Shilpi', verbose_name='\u0997\u09c0\u09a4\u09bf\u0995\u09be\u09b0'),
        ),
        migrations.AlterField(
            model_name='gaan',
            name='shilpi',
            field=models.ManyToManyField(blank=True, null=True, related_name='ga_voice', to='album.Shilpi', verbose_name='\u09b6\u09bf\u09b2\u09cd\u09aa\u09c0'),
        ),
    ]
