# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0033_auto_20160315_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaan',
            name='video',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
