# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0034_auto_20160315_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaan',
            name='sound',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u09b8\u09be\u0989\u09a8\u09cd\u09a1\u0995\u09cd\u09b2\u09be\u0989\u09a1'),
        ),
        migrations.AlterField(
            model_name='gaan',
            name='video',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u0987\u0989\u099f\u09bf\u0989\u09ac'),
        ),
    ]
