# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0035_auto_20160315_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaan',
            name='surokar',
            field=models.ManyToManyField(blank=True, null=True, related_name='ga_tune', to='album.Shilpi', verbose_name='\u09b8\u09c1\u09b0'),
        ),
    ]
